button_icon:
  type: string
  default: "magic"
button_title:
  type: string
  default: "Dropdown"
no_button_title_on_mobile:
  type: bool
  default: false
dropdown_items:
  type: list
  default: "hat-wizard, Wizard 1, /|frog, Wizard 2, /"
  description:
    en: "Comma delimited in this order:</br>
    <b>Icon, Text, URL</b><br>
    <b>Icon:</b> the name of the Fontawesome icon to be used<br>
    <b>Text:</b> the visible text of the menu item<br>
    <b>URL:</b> the URL you want the item to point to"
new_topic_icon:
  type: string
  default: "plus"
new_topic_title:
  type: string
  default: "New Topic"
Svg_icons:
  type: list
  list_type: compact
  default: "hat-wizard|frog"
  description:
    en: "Include FontAwesome 5 icon classes for each icon used in the list."