button_icon:
  type: string
  default: "magic"
button_title:
  type: string
  default: "Dropdown"
hide_button_title_on_mobile:
  type: bool
  default: false
show_button_to_visitors:
  type: bool
  default: false
dropdown_items:
  type: list
  default: "hat-wizard, Wizard 1, /|frog, Wizard 2, /"
  description:
    en: "Comma delimited in this order:</br>
    <b>Icon, Text, URL, (optional CSS class-name)</b><br>
    <b>Icon:</b> the name of the Fontawesome icon to be used<br>
    <b>Text:</b> the visible text of the menu item<br>
    <b>URL:</b> the URL you want the item to point to<br>
    <b>CSS class-name:</b> an optional class-name to target the menu item"
new_topic_as_dropdown:
  type: bool
  default: true
new_topic_icon:
  type: string
  default: "plus"
new_topic_title:
  type: string
  default: "New Topic"
hide_default_new_topic_button:
  type: bool
  default: false
Svg_icons:
  type: list
  list_type: compact
  default: "hat-wizard|frog"
  description:
    en: "Include FontAwesome 5 icon classes for each icon used in the list."